#lubianat may 2019
# csv files were manually downloaded for pubmed searches by each disease title.


library(data.table)
library(tidyr)
temp = list.files(pattern="*.csv")
temp_names <- gsub('.csv', '\\1', temp)
myfiles = lapply(temp, read.csv)
myfiles = lapply(myfiles, separate, sep = ',', col = 1, into = c('counts')) 
myfiles = lapply(myfiles,rownames_to_column, var = 'year')
myfiles = lapply(myfiles, function(x){
  x <- x[-1,]
})

for (i in 1:5){
  myfiles[[i]]$disease <- temp_names[[i]]
  
}

full_disease_table <- myfiles %>% reduce(full_join)
full_disease_table$counts <- as.numeric(full_disease_table$counts)
# CODE BASED ON Nitish @ stackoverflow (https://stackoverflow.com/questions/53162821/animated-sorted-bar-chart-with-bars-overtaking-each-other)


full_disease_table_transformed <- full_disease_table %>%
  filter(year > 1970) %>%
  group_by(year) %>%
  # The * 1 makes it possible to have non-integer ranks while sliding
  mutate(rank = min_rank(-counts) * 1,
         counts_rel = counts/counts[rank==1],
         counts_lbl = paste0(" ",counts)) %>%
  ungroup()


full_disease_table_transformed$counts <- round(full_disease_table_transformed$counts)

p <- ggplot(full_disease_table_transformed, aes(rank, group = disease, 
                     fill = as.factor(disease), color = as.factor(disease))) +
  geom_tile(aes(y = counts/2,
                height = counts,
                width = 0.9), alpha = 0.8, color = NA) +
  geom_text(aes(y = 0, label = paste(disease, " ")), vjust = 0.2, hjust = 1) +
  geom_text(aes(y=counts,label = counts, hjust=0)) +
  coord_flip(clip = "off", expand = FALSE) +
  scale_y_continuous(labels = scales::comma) +
  scale_x_reverse() +
  guides(color = FALSE, fill = FALSE) +
  
  labs(title='{closest_state}', x = "", y = "PubMed articles about flavivirus - diseases",
       caption = "Sources: PubMed| Plot generated by Tiago Lubiana @lubianat") +
  theme(plot.title = element_text(hjust = 0, size = 22),
        axis.ticks.y = element_blank(),  # These relate to the axes post-flip
        axis.text.y  = element_blank(),  # These relate to the axes post-flip
        plot.margin = margin(1,1,1,4, "cm")) +
  
  transition_states(year, transition_length = 4, state_length = 1) +
  ease_aes('cubic-in-out')
p
anim <- animate(p , end_pause = 1)
anim_save(filename = 'basic_flavivirus_race.gif')
